### ISSUE TITLE
Atomic design

### ISSUE THREAD

**Issue by beltz18** [JDRL555/Post-Yourself#1]
before to start this project i gotta give you a very important advice. When we write clean, optimal and reusable code in React we have to take some points before to die attempting.

Atomic design is a methodology pattern that lead us to make small components which can be combined into other components, simplifying our workspace.

Let's imagine a simple scenary to clear this point: we have to build a component called post, this post contains a header, a body and a footer. Inside the header we have the profile photo from poster and it's name, in body, the description of the post and multimedia resources (such as photos, videos, links, etc), and finally, in footer we'll have the commets section for this post.

We can simplify all this big component called post into smaller components, by example: header, body and footer components, and even more smaller components like: resource, description, comment, profile or even button components.

The main purpose of atomic design it's 'encapsulate' every single part of the post component in smaller components, this allow us to manipulate our code, debug and testing very well and efficiently.

Good luck in your project bro 😉😉

**Comment by JDRL555** [comment]
Thank you so much for your advise. I'll take it for upgrade my testing
project. Well, if we're literal, React's logo is an atom for a reason 😅.
Thank you, and good look with your work!
